# Site settings
title: pone "hola mundo!"
header-img: img/home-bg.png
email: blackbeltdiaries@gmail.com
copyright_name: MonksAndNinjas
description: > # this means to ignore newlines until "baseurl:"
  "Nadia! I really like this, I think I wanna learn to code!"
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MonksAndNinjas
learn_profile: MonksAndNinjas
email_username: blackbeltdiaries@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
